# Generated by Django 3.2.12 on 2022-06-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20200524_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
