# Generated by Django 4.0.2 on 2023-02-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_lot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
